### ISSUE TITLE
[Dataset] The Mismatch of prepareing datasets

### ISSUE THREAD

**Issue by henrytsui000** [chengche6230/ReST#13]
Hi @chengche6230,

I hope this message finds you well. Firstly, I want to express my appreciation for your incredible work. Your efforts are greatly valued.
I've encountered some challenges while preparing the datasets, and I'm hoping you can assist me in resolving them.
Here are the specific issues I've encountered with each dataset:

- ### CAMPUS:
We've attempted to download the dataset from the provided [Website](https://bitbucket.org/merayxu/multiview-object-tracking-dataset/src/master/), as well as through the links provided in #1  and #4 . However, upon inspection, it seems that the CAMPUS dataset contains four scenes (Auditorium, Garden1, Garden2, Parkinglot), whereas the key of provided json (i.e. `./datasets/CAMPUS/metainfo.json `) does not include Auditorium. Furthermore, the annotations are named differently. For instance, the annotations required by
https://github.com/chengche6230/ReST/blob/b166d4d3f2e73390b7c8df634ccca39a6de62417/src/datasets/preprocess.py#L254
https://github.com/chengche6230/ReST/blob/b166d4d3f2e73390b7c8df634ccca39a6de62417/datasets/CAMPUS/metainfo.json#L4
are named `[view-c0.txt, view-c1.txt, view-c2.txt, view-c3.txt]`, while the files downloaded from the link are named `[view-Contour2.txt, view-HC2.txt, view-HC3.txt, view-IP1.txt]`. Additionally, the [calibration matrix](https://bitbucket.org/merayxu/multiview-object-tracking-dataset/src/master/CAMPUS/Garden1/cam_param.mat) in the Website (i.e. `./Garden1/cam_param.mat`) does not match the homography matrix in provided `./CAMPUS/metainfo.json`.

- ### Wildtrack:
We've attempted to download the dataset from the [Official Website](https://www.epfl.ch/labs/cvlab/data/data-wildtrack/). However, we've encountered difficulties in unzipping the file. It appears to contain a loop-folder structure, preventing us from obtaining the annotation files. Could you provide the annotations or offer some advice on successfully unzipping the file?

- ### PETS09:
We downloaded the zip file from MOT15, but it seems that the S2L1 folder (the folder containing annotations at ./datasets/PETS09) only contains data from one camera. We cannot find another view or perspective. Additionally, the provided folder contains five files, i.e., `[View_001.txt, View_005.txt, View_006.txt, View_007.txt, View_008.txt]`. However, the script src/datasets/preprocess.py requires files named `[View_000.txt, View_001.txt, View_002.txt, View_003.txt, View_004.txt]`.

Your guidance and assistance in resolving these issues would be immensely appreciated. Thank you for your time and support.

Best regards,
Hao-Tang Tsui

**Comment by chengche6230** [comment]
Hi,

Thanks for your interest in our research at first.

### Campus
* Yes, there are four scenes in their dataset, but the auditorium sequence doesn't have a fully overlapping camera layout. Therefore, we only use the sequence w/ overlapping FoV in our paper. The experiment of non-overlapping / partially overlapping sequences will be included in our future research.
* The mismatch of naming patterns can be fixed by yourself. We did so just for convenience while processing massive datasets.
* The homography matrix in CAMPUS is calculated by ourselves because we found the provided one isn't available. For more details, pls refer to this [issue](https://github.com/chengche6230/ReST/issues/9#issuecomment-2007662379).

### Wildtrack
* We also encountered many problems downloading this dataset lol. Maybe you can change your browser or network. Downlaod link of annotation files [here](https://drive.google.com/drive/folders/1ToQBK60Jh9S3IfyrCbIH0-hibaMqV6mH?usp=sharing).

### PETS09
* Again, the naming pattern is just for the experiment's convenience. Sorry for the misleading. Please double check the txt files before experiement.

Best
Cheng-che
