### ISSUE TITLE
Question about non-overlapping scenario

### ISSUE THREAD

**Issue by dlsrbgg33** [chengche6230/ReST#5]
Hi, thanks for the great work and provided code.
As what title says, I am curious about how I can apply your method to non-overlapping scenarios.
Do I have to skip the projection feature for association?
According to the paper, you also did experiment on Auditorium where the FOV of cameras are not overlapped. I am wondering the training and inference setups for this scenario.
It would be appreciated if you can provide guide on this.

**Comment by chengche6230** [comment]
Hi,
In our work, we focus more on the overlapping FoV scenarios. The sequence of Auditorium is partially overlapping with 2 cameras in both scenes. As for purely non-overlapping scenarios, you need to redesign the feature you need, e.g., rely more on appearance features rather than geometry positions, which have no effect for associating across different views.

As for the experiment details about Auditorium, the projection feature still works. Project each detection in the specific ground plane with appropriate offset. For example, people in the lobby will be projected onto the plane A, which x in [0, MAX_X] and y in [0, MAX_Y], while people in the room will be projected onto the plane B, which x in [0 + OFFSET_X, MAX_X + OFFSET_X] and y in [0 + OFFSET_Y, MAX_Y + OFFSET_Y].

**Comment by dlsrbgg33** [comment]
Thank you, it is clear to me.
