### ISSUE TITLE
Detection part

### ISSUE THREAD

**Issue by Ququqq** [chengche6230/ReST#7]
Hello, thank you very much for sharing the code. I am a newbie and recently wanted to try running your code and had a lot of problems along the way. I'd appreciate it if you could help me with my doubts.
1. Question1:  Prepare all image frames as {FRAME}_{CAM}.jpg in /output/frames.   
     This line of commentary of yours, doesn't it distinguish which camera is shooting the footage? For example, there are two cameras with a total of 200 frames. The file name is eg.1_CAM --200_CAM? Can you look at the image form under your folder.
2. Question2: Select what input detection you want, and modify MODEL.DETECTION
     Where do I download the testing section
     Looking forward to your reply. Can't wait to contact you ，my email：ququu0201@163.com
                                                                        thanks

**Comment by chengche6230** [comment]
Hi,

Sorry for not getting back to you sooner because of the day-off.

### Question 1
The name of image frames will be like:

- 0_0.jpg
- 0_1.jpg
- 1_0.jpg
- 1_1.jpg
- ...
- 199_0.jpg
- 199_1.jpg

### Question 2
For groundtruth detection, you can access it via directly modifying MODEL.DETECTION to 'gt'. As for the custom detection, you need to prepare the detection file following the same format as gt_test.json first.
